### PR TITLE
Accounted for two word last names in eml_nsf_to_project

### LINKED ISSUE #188: eml_nsf_to_project extracts multi-word last names incorrectly
Noticed it when running this funding number:
`eml_nsf_to_project("1822406")`

Maria Val Martin is extracted as Maria artin instead.

Likely has something do with the regex in the function.

### PR DESCRIPTION
**Pull request by eeerika**
- fixed `eml_nsf_to_project` parsing two word last names (like "Val Martin") incorrectly

resolves #188

### CODE REVIEW

**Comment by laijasmine** [comment]
@eeerika can you add a test to the test_eml.R file that checks that `eml_nsf_to_project` parses the names properly? You can use something like:
```
proj <- eml_nsf_to_project("1822406", eml_version = "2.2")

expect_equal(proj$personnel$individualName$givenName, "name")

 ```

File: tests/testthat/test_eml.R [hunk 1]
```diff
@@ -478,6 +478,11 @@ test_that('eml_nsf_to_project fails gracefully', {
 
 })
 
+test+that('eml_nsf_to_project parses two-word last names correctly', {
+  proj <- eml_nsf_to_project("1822406", eml_version = "2.2")
+
+  expect_equal(proj$personnel$individualName$givenName, "name")
```
Comment (laijasmine) [inline tests/testthat/test_eml.R:484]: I suspect the Travis checks will fail here. Hint - what are we expecting `proj$personnel$individualName$givenName` to equal to (the second argument)?

**Review by laijasmine — CHANGES_REQUESTED** [review]
a minor tweak but great work!

**Review by laijasmine — APPROVED** [review]

File: tests/testthat/test_eml.R [hunk 2]
```diff
@@ -478,6 +478,11 @@ test_that('eml_nsf_to_project fails gracefully', {
 
 })
 
+test+that('eml_nsf_to_project parses two-word last names correctly', {
```
Comment (laijasmine) [inline tests/testthat/test_eml.R:481]: syntax error here

File: tests/testthat/test_eml.R [hunk 3]
```diff
@@ -481,7 +481,8 @@ test_that('eml_nsf_to_project fails gracefully', {
 test_that('eml_nsf_to_project parses two-word last names correctly', {
   proj <- eml_nsf_to_project("1822406", eml_version = "2.2")
 
-  expect_equal(proj$personnel$individualName$givenName, "Maria Val Martin")
+  expect_equal(proj$personnel$individualName$givenName, "Maria")
```
Comment (laijasmine) [inline tests/testthat/test_eml.R:484]: realized this fails because there is more than one personnel in a given project!
